services:
  - type: web
    name: comet-backend
    runtime: node
    plan: free
    region: oregon
    healthCheckPath: /api/health
    buildCommand: npm install && npx nx build backend
    startCommand: cd apps/backend && node dist/main.js
    envVars:
      - key: ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api
      - key: FRONTEND_DOMAIN
        value: https://comet-frontend.onrender.com
      - key: BACKEND_DOMAIN
        value: https://comet-backend.onrender.com
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_SSL_ENABLED
        value: "true"
      - key: DATABASE_REJECT_UNAUTHORIZED
        value: "false"
      - key: FILE_DRIVER
        value: s3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_S3_BUCKET
        sync: false
      - key: AWS_S3_REGION
        value: auto
      - key: AWS_S3_ENDPOINT
        sync: false
      - key: AWS_S3_FORCE_PATH_STYLE
        value: "false"
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: comet-frontend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && NEXT_PUBLIC_API_URL=http://$COMET_BACKEND_HOSTPORT npx nx build frontend
    startCommand: cd apps/frontend && NEXT_PUBLIC_API_URL=http://$COMET_BACKEND_HOSTPORT npx next start -p ${PORT:-10000}
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_ENV
        value: production
      - key: COMET_BACKEND_HOSTPORT
        fromService:
          type: web
          name: comet-backend
          property: hostport
